#!/usr/bin/env node
// Compile src/styles/design-system.css (Tailwind, scanning web/ and the model's mockups in ../workspace.json)
// into the board's design-system snippet: ../snippets/design-system.html, a single <style> block.
//
//   npm run design-system                      # writes ../snippets/design-system.html
//   npm run design-system -- --out <file>      # writes somewhere else (to look before replacing)
//
// Then `emcli sync push` sends the snippet, and every wireframe that imports it is restyled.
import { execFileSync } from "node:child_process"
import { mkdirSync, readFileSync, writeFileSync } from "node:fs"
import { dirname, join, relative, resolve } from "node:path"
import { fileURLToPath } from "node:url"

const web = resolve(dirname(fileURLToPath(import.meta.url)), "..")
const args = process.argv.slice(2)
const outAt = args.indexOf("--out")
const out = resolve(outAt >= 0 && args[outAt + 1] ? args[outAt + 1] : join(web, "..", "snippets", "design-system.html"))

const css = execFileSync(
    join(web, "node_modules", ".bin", "tailwindcss"),
    ["--input", join(web, "src", "styles", "design-system.css"), "--minify"],
    { cwd: web, encoding: "utf8", stdio: ["ignore", "pipe", "inherit"] }
)
const board = readFileSync(join(web, "src", "styles", "board.css"), "utf8").replace(/\/\*[\s\S]*?\*\//g, "").trim()

const html = [
    "<!-- Generated by `npm run design-system` in web/ from web/src/styles/design-system.css. Edit that file, not this one. -->",
    "<style>",
    css.trim(),
    board,
    "</style>",
    ""
].join("\n")

mkdirSync(dirname(out), { recursive: true })
writeFileSync(out, html)
console.log(`Wrote ${relative(process.cwd(), out) || out} (${Math.round(html.length / 1024)} KB). Push it: emcli sync push`)
