/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/change-course-capacity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change a course's capacity */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "Idempotency-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateCourseCapacityBody"];
                };
            };
            responses: {
                /** @description Done */
                204: {
                    headers: {
                        ETag: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The body failed validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Course not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description New capacity is the same as the current one */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course-details/{courseId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a course */
        get: {
            parameters: {
                query?: never;
                header?: {
                    "If-None-Match"?: string;
                    Prefer?: string;
                };
                path: {
                    courseId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        ETag: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Course"];
                    };
                };
                /** @description Course not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Prefer: wait timed out */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/course-list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List courses (keyset-paginated) */
        get: {
            parameters: {
                query?: {
                    limit?: string;
                    cursor?: string;
                };
                header?: {
                    "If-None-Match"?: string;
                    Prefer?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        ETag: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: components["schemas"]["Course"][];
                            cursor?: string;
                        };
                    };
                };
                /** @description Prefer: wait timed out */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream events as Server-Sent Events */
        get: {
            parameters: {
                query?: {
                    after?: string;
                    types?: string;
                    tags?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/event-stream": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register-course": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a course */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "Idempotency-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterCourseBody"];
                };
            };
            responses: {
                /** @description Done */
                204: {
                    headers: {
                        ETag: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The body failed validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Course already exists */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/register-student": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a student */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "Idempotency-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterStudentBody"];
                };
            };
            responses: {
                /** @description Done */
                204: {
                    headers: {
                        ETag: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The body failed validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Student already exists */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/student-details/{studentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a student */
        get: {
            parameters: {
                query?: never;
                header?: {
                    "If-None-Match"?: string;
                    Prefer?: string;
                };
                path: {
                    studentId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        ETag: string;
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Student"];
                    };
                };
                /** @description Student not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Prefer: wait timed out */
                504: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subscribe-student-to-course": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Subscribe a student to a course */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "Idempotency-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SubscribeStudentBody"];
                };
            };
            responses: {
                /** @description Done */
                204: {
                    headers: {
                        ETag: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The body failed validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Course or student not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Course is full, or the student is already subscribed */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/unsubscribe-student-from-course": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unsubscribe a student from a course */
        post: {
            parameters: {
                query?: never;
                header?: {
                    "Idempotency-Key"?: string;
                };
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UnsubscribeStudentBody"];
                };
            };
            responses: {
                /** @description Done */
                204: {
                    headers: {
                        ETag: string;
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description The body failed validation */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
                /** @description Course or subscription not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["ProblemDetails"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ProblemDetails: {
            /** @example 422 */
            status: number;
            /** @example Unprocessable Entity */
            title: string;
            /** @example Course is full */
            detail: string;
            /** @example about:blank */
            type?: string;
            instance?: string;
        };
        UpdateCourseCapacityBody: {
            /**
             * @description ID of the course
             * @example course-101
             */
            courseId: string;
            /**
             * @description New maximum student capacity
             * @example 50
             */
            newCapacity: number;
        };
        Course: {
            /** @example course-101 */
            id: string;
            /** @example Introduction to TypeScript */
            title: string;
            /** @example 30 */
            capacity: number;
            subscribedStudents: {
                studentId: string;
                name: string;
                studentNumber: number;
            }[];
        };
        RegisterCourseBody: {
            /**
             * @description Unique course identifier
             * @example course-101
             */
            id: string;
            /**
             * @description Course title
             * @example Introduction to TypeScript
             */
            title: string;
            /**
             * @description Maximum number of students
             * @example 30
             */
            capacity: number;
        };
        RegisterStudentBody: {
            /**
             * @description Unique student identifier
             * @example student-1
             */
            id: string;
            /**
             * @description Student full name
             * @example Alice
             */
            name: string;
        };
        Student: {
            /** @example student-1 */
            id: string;
            /** @example Alice */
            name: string;
            /** @example 1 */
            studentNumber: number;
            subscribedCourses: {
                courseId: string;
                title: string;
                capacity: number;
            }[];
        };
        SubscribeStudentBody: {
            /**
             * @description ID of the course
             * @example course-101
             */
            courseId: string;
            /**
             * @description ID of the student to subscribe
             * @example student-1
             */
            studentId: string;
        };
        UnsubscribeStudentBody: {
            /**
             * @description ID of the course
             * @example course-101
             */
            courseId: string;
            /**
             * @description ID of the student to unsubscribe
             * @example student-1
             */
            studentId: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
